### ISSUE TITLE
Hi,everyone i want to get each VF desktop RGBA data how can I do?

### ISSUE THREAD

**Issue by jamaik7** [GPUOpen-LibrariesAndSDKs/MxGPU-Virtualization#32]
I passthrough the VF into qemu-kvm and I want to get the windows desktop through VRAM, how can i get the data？ thanks

**Comment by ljymonk** [comment]
this question is not related with virtualization,thus you should get the answer elsewhere 
while for linux guest system, you can do it by invoke libdrm interface, something like getcrtc(), ... I forget the details 
for Windows guest , you need to learn it from MSDN, there should be WDDM interface could be used
